### PR TITLE
only return strings from routes fixes #374

### LINKED ISSUE #374: Wrong Content-Length for small amounts of data via IO.copy
Minimal example:

``` crystal
require "kemal"

DATA = "foo"

get "/" do |context|
  context.response.content_length = DATA.bytesize
  IO.copy(IO::Memory.new(DATA), context.response)
end

spawn { Kemal.run(3000) }
sleep 1

HTTP::Client.get("http://localhost:3000") do |response|
  puts "Expected: #{DATA.inspect}"
  puts "Received: #{response.body_io.gets_to_end.inspect}"
end
```

You will see that the received data differs from the original. This is an issue with Kemal itself since if you replace kemal in this case with a pure `HTTP::Server` it will be handled correctly.

### PR DESCRIPTION
**Pull request by crisward**

### CODE REVIEW

**Comment by sdogruyol** [comment]
I had some hesitations about this but couldn't come up with any better idea for now. LGTM :+1:

**Comment by crisward** [comment]
I also can't help thinking someone is possibly relying on this behaviour, perhaps flag it on your change log. I'm pretty sure all my output is json or html strings. No output is much easier to spot than an extra character, so at least it's more obvious.

**Comment by sdogruyol** [comment]
@crisward let's add a breaking changelog entry for this

**Comment by bigbenz8** [comment]
Is there any progress ?

**Comment by straight-shoota** [comment]
@bigbenz8 This has been merged and should be in the latest release, `0.22.0`.

**Pull request merged**
