### PR TITLE
Serve index.html when GET / route is missing

### PR DESCRIPTION
**Pull request by Yashko**
### Description of the Change

I started developing my application using Kemal and i was disappointed when i created /public folder and index.html file inside, and Kemal doesn't send it to me. I think it should be default behavior if 
`get "/" do`
is missing. But in case of index.html AND specified handler for root path (get "/" do), it should execute handler.

### Alternate Designs

Any suggestions are welcome

### Benefits

Now you don't need specify send_file("index.html") if you want just to send index.html file by default

### Possible Drawbacks

none i guess

### CODE REVIEW

**Comment by crisward** [comment]
Serving index.html in the root could be useful for client side apps. But I'm not sure if this goes far enough. Should you also not do this recursively into sub-directories? Also what about being able to specify the name of your default file? (default.html, index.html. index.html etc..)  

Have you re-ordered the middleware? If so, was this necessary?

**Comment by straight-shoota** [comment]
Kemal is an application framework, not a webserver. It should not expose *any* files by default.

It could be considered to have a simple way to *add* such a feature, but it should be opt-in, not default.

**Comment by crisward** [comment]
It should perhaps be added to the static file options 
http://kemalcr.com/guide/#static-file-options

Perhaps
```
serve_static({"gzip" => true, "dir_listing" => false,"dir_index":"index.html"})
```

Apache has `DirectoryIndex` and nginx has `try_files`, think the above is more in keeping with the current naming. It's also something that should be proposed to Crystal's static file handler - https://crystal-lang.org/api/0.23.1/HTTP/StaticFileHandler.html.

**Comment by sdogruyol** [comment]
This is out of scope, for now :+1: I'm also thinking of splitting `StaticFileHandler` out of Kemal. Maybe we can implement this after that.

**Pull request closed without merging**
