### PR TITLE
Fix an issues with responding with long strings

### PR DESCRIPTION
**Pull request by mamantoha**
Fixes https://github.com/kemalcr/kemal/issues/575

This change works for me.

/cc @bcardiff maybe you can provide more information about this issue. Thanks.

### CODE REVIEW

**Comment by nickbclifford** [comment]
Would love to see this merged, I'm currently blocked on upgrading to 0.35.0 by this exact problem.

**Comment by bcardiff** [comment]
I think is needed because of the changes in https://github.com/crystal-lang/crystal/pull/9115/files .

The change seems good.

**Comment by mamantoha** [comment]
@bcardiff there is another issue with WebSockets related to this changes in Crystal.

I created a fix in https://github.com/kemalcr/kemal/pull/577

@sdogruyol it would be nice if you will able to review both.

Thanks.

**Comment by xaviablaza** [comment]
This change works for me, would love to see this merged as it fixes static files infinitely loading on crystal 0.35.1.

**Pull request merged**
