### PR TITLE
fix for #399

### PR DESCRIPTION
**Pull request by crisward**
This seems to fix it. Would you like me to update the travis tests to run in --release too? This would have failed if that had been set.

### CODE REVIEW

**Comment by sdogruyol** [comment]
Thank you :pray: @crisward , that'd be awesome :100:

**Comment by crisward** [comment]
This is failing because travis has `Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1` I think it needs LLVM 4.0 to compile with --release due to a bug in LLVM. No idea how to get travis to pull a later llvm version.

**Comment by crisward** [comment]
all passing now

**Comment by sdogruyol** [comment]
LGTM :+1: Thanks @crisward

**Pull request merged**
