### PR TITLE
add support for multiple worker processes

### PR DESCRIPTION
**Pull request by jreinert**
### Description of the Change

This allows spawning multiple worker processes to handle requests on multi-core environments. It makes use of the reuse_port option in HTTP::Server (or TCPServer).

### Benefits

Should result in way higher throughput (optimally n times higher with n being the amount of workers and cpus on a host)

### Possible Drawbacks

Higher memory consumtion since fork is used.

### CODE REVIEW

**Comment by straight-shoota** [comment]
Kemal should focus on serving HTTP, not managing processes. That's a more complicated task then just calling `Process.fork` a few times. What happens for example when a process crashes?

There are sophisticated process supervisors available for any platform. Using one for managing Kemal workers is pretty simple: Just spawn the binary multiple times with `reuse_port`. There is no benefit from having custom process handling implemented directly into Kemal. Existing solutions are far more mature, offer more features and are easier to integrate with other application components.

**Comment by jreinert** [comment]
@straight-shoota that's a good point. Then at least kemal should expose the `reuse_port` setting to the `run` method. This is trivial of course.

**Comment by vlazar** [comment]
@straight-shoota I wonder what is the good reason for any server in Crystal, not only Kemal's to not support `reuse_port` either by default or dynamically.

By "by default" I mean just using `reuse_port: true` so that process can either be started once or N times. Well, for "by default" case the process started without `reuse_port: true` can error an I can see that might be needed for someone to not accidentally start multiple processes on the same port when they want to run them on different ports.

But in general, wouldn't it be nice if one wouldn't need to add `reuse_port: true` option and re-compile server just to change the way the server processes can be run with some process manager or without it.

I wonder if there is a good  way to specify `reuse_port` option from outside for any custom server, meaning it's somehow implemented in Crystal stdlib and then I can do something like:

(pseudo feature, maybe not flags but env vars or something)
`./my_kemal_server --reuse-port`
`./my_plain_crystal_server --reuse-port`

**Comment by straight-shoota** [comment]
@vlazar This was actually the case before 0.21.0 and I suggested to *not* have `reuse_port` by default in crystal-lang/crystal#4019. This behaviour is typically not expected and can be confusing. An application should fail to bind to an already occupied port unless explicitly asked to. So I would never hard code to always `reuse_port` but rather make it configurable at runtime.

Anyway, it's fairly easy to switch this feature on, but it should not be the default.

**Comment by vlazar** [comment]
@straight-shoota Thanks for the link! Yes, absolutely agree on that it's confusing when it's hardcoded as `reuse_port: true`.

What I was thinking about is that it would be nice to have a standard way fro all servers written in any framework in Crystal to be able to be run either in as 1 process on N processes with or without reuse port with no effort. Something like in Ruby you can use Puma and just configure the number of workers required.

**Comment by sdogruyol** [comment]
Thanks for the PR @jreinert :+1: As @straight-shoota stated there are many great tools available for process management and it shouldn't be Kemal's responsibility :+1:

**Pull request closed without merging**
