### PR TITLE
User defined context store types

### PR DESCRIPTION
**Pull request by neovintage**
Here's my use case. The problem I'm having is that in middleware, filters or between methods, I want to store an object and not necessarily a base type. When I want an object, I end up polluting the `HTTP::Server::Context` class. I'd much prefer to be able to store the object in context storage. 

Here's a contrived example:

```crystal
require "kemal"

class MyType
  property name
  @name = "kemal"
end

HTTP::Server::Context.add_store_type(MyType)

before_get "/" do |env|
  t = MyType.new
  t.name = "awesome"
  env.set "my_type", t
end

get "/" do |env|
  t = env.get("my_type").as(MyType)
  t.name
end
```

### CODE REVIEW

**Comment by sdogruyol** [comment]
@neovintage wow, this is great 👍 I actually tried to achieve that a long time ago but there wasn't any `macro finished` 😄

**Comment by sdogruyol** [comment]
How about having a more friendlier and shorter method like `add_store_type`?

**Comment by neovintage** [comment]
@sdogruyol I would still like to namespace the method so that you know you're working with Kemal. What about `Kemal.add_context_store_type`?

**Comment by neovintage** [comment]
@sdogruyol any thoughts?

**Comment by sdogruyol** [comment]
@neovintage i like this, however i'm thinking about the namespacing. As you already know all helpers are in global space and this breaks that convention. 

IMHO we either have them at global scope or Kemal scope. WDYT?

**Comment by crisward** [comment]
FWIW I like name spaced stuff, less magic, easier to find source of method. 

Though anyone using Kemal would need to do lots of updates if you switched. Perhaps all new ones could be namespaced, with the option for old ones, then deprecate them with a major version bump. Not sure if it's possible to output warnings in the interim? (like react.js does?)

**Comment by neovintage** [comment]
@sdogruyol @crisward I could go either way. If we want to put it in the global context, I think that's fine. The more important part for me is the functionality itself. I think it's entirely your call @sdogruyol. Let me know what you want to do and I'll change it accordingly

**Comment by neovintage** [comment]
@sdogruyol macro is now in global scope. should be good to go

**Comment by sdogruyol** [comment]
Great 👍  Thank you @neovintage, this is awesome 💯

**Comment by samueleaton** [comment]
fyi https://github.com/crystal-lang/crystal/pull/3612#issuecomment-294902336

**Pull request merged**
