### PR TITLE
Multipart form params and files

### PR DESCRIPTION
**Pull request by crisward**
I don't mind adding docs and tests. Just let me know what you think.
The tmp file removing seems a bit out of place, but I'm not sure what better place there is.

I've manually tested this and it works fine in combination with kemal-csrf and kemal-session.

### CODE REVIEW

**Comment by sdogruyol** [comment]
@crisward could you please tell the specific use case for this

**Comment by crisward** [comment]
* It allows forms with `enctype="multipart/form"` to be treated the same as other forms.
* It fixes https://github.com/kemalcr/kemal-csrf/issues/3
* It simplifies handling uploads to 
```
post "/uploads" do |ctx|
  file = ctx.params.files["myfile"]
  file_path = ::File.join [Kemal.config.public_folder, "images/", file.filename]
  ::File.rename(file.tmpfile, file_path)
end
```

**Comment by sdogruyol** [comment]
@crisward IMHO https://github.com/kemalcr/kemal-csrf/issues/3 should be handled in [kemal-session](https://github.com/kemalcr/kemal-session) and should only be related to `csrf`.

Having `multipart/form` should be discussed in another issue.

**Comment by crisward** [comment]
The issue I had when trying to solve using csrf's with multipart forms was, if I read the multipart data in the csrf module, it had already been read when it got to the endpoint. So I couldn't then read it in the endpoint. The data can only be read from IO once, so this needed to be done before any other code which is going to use it, hence why I dropped down to Kemal.

I've done the above change as a standalone module too, but it patches Kemal, which is dangerous as you could choose to modify the functionality of the body parser in the future and I don't want it to be that fragile. The benefit of patching however is users of Kemal can choose to include it or not, depending on their needs. 

Handling mutipart forms is a very useful thing to have in Kemal's core. The implementation api I've added is very close to the one used in Sinatra http://www.wooptoot.com/file-upload-with-sinatra , PHP and node (with express-formidable module). They all use the concept of an extra form property with a tempfile which can either be ignored and cleaned up, or moved to somewhere useful.

Have a think, and if this not what you want, I'll add my patch to github as a separate module for others to use if they also have this issue. 

Thanks again.

**Comment by sdogruyol** [comment]
Thanks for your kind explanation @crisward. I'll take a detailed second look  tomorrow

**Comment by sdogruyol** [comment]
Closing in favor of #306. Thank you

**Pull request closed without merging**
