### PR TITLE
fix issue with simple example

### PR DESCRIPTION
**Pull request by mamantoha**
Hi @sdogruyol .

I faced a very weird issue.

With a very basic example:

```
require "kemal"

get "/" do |env|
   "Hello World!"
end

Kemal.run
```

`curl` command is endless

```
 curl http://0.0.0.0:3000
```

How to reproduce the issue:

* Ubuntu 16.04/macOS Mojave (however, 19.04 not affected by this issue)
* Crystal 0.29.0
* Latest version of Kemal

I'm not very clear why it happens.
In this PR I just revert one line of code from https://github.com/kemalcr/kemal/pull/520

/cc @Sija 

Can you test it on your local systems?

Thanks!

### CODE REVIEW

**Comment by sdogruyol** [comment]
:man_facepalming: that's why linters are hard. Ameba changing that conditions and reversing the order just broke the `Content-Length` because of the early return. Thanks @mamantoha :+1:

**Comment by Sija** [comment]
Hi, that's my fault, I'd like to fix it but blacklisting whole file is incorrect. It should be rewritten properly or added inline `# ameba:disable` comment.

**Comment by sdogruyol** [comment]
@Sija agree on that, however that issue made me realize (again) that I don't fancy linters that much :neutral_face:

**Comment by veelenga** [comment]
Ameba is not fancy enough, at least right now 😄 

But, to be honest I think it just a good example of the code which is hard to refactor and maintain. That's why linters usually complain.

**Pull request merged**
