### PR TITLE
Eliminated several seconds of delay when loading big mp4 file

### PR DESCRIPTION
**Pull request by Athlon64**
### Description of the Change

Replaced the loop of `skip` calls to a single `seek`.

### Benefits

It can save several seconds of time to load big movie file.

### CODE REVIEW

**Comment by straight-shoota** [comment]
FTR: The original implementation was introduced in #299 by [@denysvitali](https://github.com/denysvitali). I believe at this point `IO` did not implement `#seek`. This might have been the reason for a custom implementation. But `FileDescriptor#seek` already existed, so there might be some other reason.

`IO#seek` still only works with some stream types (notably `IO::FileDescriptor` and `IO::Memory`) and raises on others. But this shouldn't be a problem because the code also expects the IO to implement `#size` which is only present in those types. So the code wouldn't even compile for cases where  `IO#seek` is not implemented.

**Comment by Athlon64** [comment]
Yes, I also think there must have been some reason to code like that back then, but is this still relevant today?

**Comment by Athlon64** [comment]
The tests have failed, but I don't think it was caused by this PR itself.
What should I do next?

**Comment by straight-shoota** [comment]
Yeah, the CI failure looks unrelated. Seems like some issue with ameba.

**Comment by straight-shoota** [comment]
I rebased on https://github.com/kemalcr/kemal/tree/fix/update-ameba which should fix CI.

**Comment by Athlon64** [comment]
@straight-shoota Thanks for your kind reply!

**Review by straight-shoota — APPROVED** [review]

**Review by sdogruyol — APPROVED** [review]
This is great, thanks a lot @Athlon64 @straight-shoota 🙏

**Pull request merged**
