### PR TITLE
Rework param parser

### PR DESCRIPTION
**Pull request by sdogruyol**
### Description of the Change

This is an improvement over https://github.com/kemalcr/kemal/pull/464 with more radical way of re-implementing parameter parsing logic.

This includes:

- Remove `_method` magic param
- Remove all monkey patching from `HTTP::Request`

### Alternate Designs

None.

### Benefits

- No more `request` consumption before accessing `env.params` :tada:. Which leads to more customization like using `HTTP::FormData.parse` as you wish.

```crystal
post "/upload" do |env|
  HTTP::FormData.parse(env.request) do |upload|
    puts "Doing some custom stuff with #{upload.filename}"
    # Do as you wish
  end
end
```
 
- Performance :rocket: 

### Possible Drawbacks

- *[breaking change]* From now on to access dynamic url params in a `ws` route you have to use 

```crystal
ws "/:id" do |socket, context|
  id = context.ws_route_lookup.params["id"]
end

### CODE REVIEW

**Comment by straight-shoota** [comment]
I like removing method overrides. Though I'm not sure if such a feature is needed for some applications. But such an override can probably be implemented pretty easy as a middleware ([example](http://flask.pocoo.org/docs/1.0/patterns/methodoverrides/)). A handler supporting `X-HTTP-Method-Override` might even be an idea for Crystal stdlib...

**Comment by sdogruyol** [comment]
I feel like having a common middleware for method override might be really useful for many others. We can also put that into https://github.com/crystal-loot. WDYT @paulcsmith?

**Comment by paulcsmith** [comment]
@sdogruyol That is a fantastic idea. I don't have much time to tackle that right now but I love the idea for sure 👍

**Comment by paulcsmith** [comment]
Also ccing @drujensen and @eliasjpr since I believe they are doing more Crystal/Amber than Elorest at the moment

**Comment by sdogruyol** [comment]
Updated, since we're no longer consuming the `env.request.body` anymore I've removed `env.params.files` because it's redundant. We can use `HTTP::FormData.parse(env.request)` instead :+1:

**Comment by paulcsmith** [comment]
If it is helpful, here is the override handler used in Lucky: https://github.com/luckyframework/lucky/blob/master/src/lucky/http_method_override_handler.cr

It uses the Lucky param parser, but you could likely do something similar with the Kemal parser.

To make that handler usable for multiple libs/frameworks I think it should accept a block with the context and return a HTTP Method. Something like this:

```crystal
HttpMethodOverrideHandler.configure do
  settings.fetch_method_proc = ->(context: HTTP::Server::Context) {
    # Get and return a param
  }
end
```

I'll see if I can extract that handler but I've got a few things I need to do first

**Comment by mamantoha** [comment]
I've tried change "upload method" in my code as mentioned above, and it doesn't work.

```crystal
post "/upload" do |env|
  HTTP::FormData.parse(env.request) do |upload|
    # Do something
  end
end
```

`Exception: Failed to parse multipart message: EOF reading delimiter (HTTP::Multipart::Error)`

**Comment by icyleaf** [comment]
@sdogruyol @paulcsmith May be better to built a Crystal's version `rake` and i am working on it: https://github.com/icyleaf/salt :P

**Comment by straight-shoota** [comment]
@icyleaf But why? Crystal's equivalent of rack interface is `HTTP::Server::Handler`. And it's superior as it is based on stream IO - this is Crystal's strength. You shouldn't have to store the entire response body in memory.

It might be a good idea to have some common extension to the stdlib API which can be used by any application server, be it kemal, amber, lucky or whatever. But it should be based on the established API and not impose a new, less-efficient interface.

**Comment by icyleaf** [comment]
> It might be a good idea to have some common extension to the stdlib API which can be used by any application server, be it kemal, amber, lucky or whatever. 

I agree this, but nobody to do it now. Salt is a new try and study project which it was 100% copy from rack and does not think about high-efficient, less memory and more faster than Crystal but easy to get started quickly. 

And here is another reason why i'm working on salt: [dwarf](https://github.com/icyleaf/dwarf). of cause it still was my project. it was difficult to store session with supported frameworks.

**Comment by sdogruyol** [comment]
@mamantoha have you tried using this branch?

**Comment by mamantoha** [comment]
@sdogruyol it works :tada:

**Comment by mamantoha** [comment]
@sdogruyol well, now we should parse params manually https://github.com/mamantoha/crest/pull/94/files#diff-bc2d5bc3c5eced734d143200c2eb70d1R129

**Comment by vlazar** [comment]
@sdogruyol Is this planned to be merged soonish? 😄 

I have a stale PR https://github.com/TechEmpower/FrameworkBenchmarks/pull/3884 and was waiting for Kemal's reuse_port to work in Crystal 0.25.1. Now it works, but Crystal 0.25.1 had a serious performance regression so there was no point in merging PR to TFB with Crystal 0.25.1 to only show bad performance for Crystal frameworks.

Now that Crystal 0.26.0 with performance fix is around the corner, this PR can make things even better 😉

My hope is  frameworks would not be broken by Crystal 0.26.0 and we can have more recent benchmark  results for Crystal.

**Comment by sdogruyol** [comment]
Let's get the party started :tada:

**Pull request merged**
